nelmio_api_doc:
    documentation:
        # servers:
        #   - url: http://api.example.com/unsafe
        #     description: API over HTTP
        #   - url: https://api.example.com/secured
        #     description: API over HTTPS
        info:
            title: Cometa_rest_api
            description: Affiliate programm 
            version: 1.0.0
        # components:
        #     securitySchemes:
        #         Bearer:
        #             type: http
        #             scheme: bearer
        #             bearerFormat: JWT
        # security:
        #     - Bearer: []
        paths:
            /api/user:
                get:
                    description: Get all users
                    tags:
                        - User management
                    responses:
                        200:
                            description: ok
                            content: 
                                application/json: 
                                    schema: 
                                        type: object
                                        properties:
                                            status: { type: string, example: '0'}
                                            name: { type: string, example: 'string'}
                                            email: { type: string, example: 'ok'}
                                        
            /api/user/admin/{userId}:
                post:
                    description: Show user
                    tags:
                        - User management
                    parameters:
                        - in: query
                          name: user
                          required: true
                          schema:
                            type: string
                            
                    responses:
                        200:
                            description: user data
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: '#/components/schemas/User'
            /api/user/admin/{id}:
                get:
                    description: Show user Id
                    tags:
                        - User management
                    parameters:
                        - in: path
                          name: userId
                          required: false
                          schema:
                            type: string
                    # parameters:
                        - in: path
                          name: email
                          required: false
                          schema:
                            type: string
                            
                    responses:
                        200:
                            description: user data Id
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: '#/components/schemas/UserDTO'
                    # parameters:
                    #     - in: query
                    #       name: name
                    #       schema:
                    #         type: string
                    # responses:
                    #     200:
                    #         description: name data
                    #         content: 
                    #             application/json: 
                    #                 schema: 
                    #                     $ref: #/components/schemas/UserResponse    
                # get:
                #     description: Show user
                #     tags:
                #         - user
                #     responses:
                #         200:
                #             description: ok
                #             content: 
                #                 application/json: 
                #                     schema:
                #                         type: object
                #                         properties:
                #                             status: { type: string, example: 'ok'}
            /api/pakege/new/{user_id}:
                post:
                    description: New pakage 
                    tags:
                        - Package management 
                    parameters:
                        - in: path
                          name: user_id
                          required: true
                          schema:
                            type: string
                        - in: query
                          name: referral_link
                          required: true
                          schema:
                            type: string
                        - in: query
                          name: email_user
                          required: true
                          schema:
                            type: string
                        - in: query
                          name: pakage_table_id
                          required: true
                          schema:
                            type: string
                         
                    
                    responses:
                        200:
                            description: New pakage
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: #/components/schemas/UserResponse 
            /api/pakege/show/{user_id}:
                get:
                    description: Show user pakages 
                    tags:
                        - Package management 
                    parameters:
                        - in: path
                          name: user_id
                          required: true
                          schema:
                            type: string
                    responses:
                        200:
                            description: Show user pakages
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: #/components/schemas/UserResponse 
            /api/referral/new/{pakage_id}:
                post:
                    description: Create New referral 
                    tags:
                        - Referral management 
                    parameters:
                        - in: path
                          name: pakage_id
                          required: true
                          schema:
                            type: string
                        - in: query
                          name: user_id
                          required: true
                          schema:
                            type: string
                        - in: query
                          name: referral_name
                          required: true
                          schema:
                            type: string
                    responses:
                        200:
                            description: Create New referral network
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: #/components/schemas/UserResponse 
            /api/referral/admin:
                get:
                    description: Show all referral 
                    tags:
                        - Referral management 
                    responses:
                        200:
                            description: Show all referral network
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: '#/components/schemas/ListReferralNetworks' 
            /api/network/new/{pakage_id}:
                post:
                    description: Create New network user 
                    tags:
                        - Network management 
                    parameters:
                        - in: path
                          name: pakage_id
                          required: true
                          schema:
                            type: string
                        # - in: query
                        #   name: user_id
                        #   required: true
                        #   schema:
                        #     type: string
                        # - in: query
                        #   name: referral_link
                        #   required: true
                        #   schema:
                        #     type: string
                    responses:
                        200:
                            description: Create New network user
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: #/components/schemas/UserResponse 
            /api/network/total/balance/{user_id}:
                get:
                    description: The total balance of all my places 
                    tags:
                        - Network management 
                    parameters:
                        - in: path
                          name: user_id
                          required: true
                          schema:
                            type: integer
                    responses:
                        200:
                            description: The total balance of all my places
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: #/components/schemas/UserResponse 
            /api/network/myteam/{pakage_id}:
                get:
                    description: My Team
                    tags:
                        - Network management 
                    parameters:
                        - in: path
                          name: pakage_id
                          required: true
                          schema:
                            type: integer
                    responses:
                        200:
                            description: My Team
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: '#/components/schemas/ReferralNetwork' 
            /api/network/show/{pakage_id}:
                get:
                    description: Show my place
                    tags:
                        - Network management 
                    parameters:
                        - in: path
                          name: pakage_id
                          required: true
                          schema:
                            type: integer
                    responses:
                        200:
                            description: Show my place
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: '#/components/schemas/ReferralNetwork' 
            /api/network/mail_referral/{pakage_id}:
                post:
                    description: Show my place
                    tags:
                        - Network management 
                    parameters:
                        - in: path
                          name: pakage_id
                          required: true
                          schema:
                            type: integer
                        - in: query
                          name: email_to_client
                          required: true
                          schema:
                            type: string
                    responses:
                        200:
                            description: Show my place
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: '#/components/schemas/ReferralNetwork' 
            /api/network/admin:
                get:
                    description: List of all revenge in line 
                    tags:
                        - Network management 
                    responses:
                        200:
                            description: List of all revenge in line
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: '#/components/schemas/ReferralNetwork' 
                    # requestBody:
                    #     description: A JSON object containing pet information
                    #     content:
                    #     application/json:
                    #         schema:
                    #         oneOf:
                    #             - $ref: #/components/schemas/UserResponse                                                      
        tags: 
           - name: User management
           - name: Package management
           - name: Network management 
           - name: Referral management    
        components:   
            schemas:
                NetworkDTO:
                    description: Network table      
                    type: object
                    properties:
                        User Id: { type: integer, example: 'integer'}   
                UserDTO:
                    description: User table      
                    type: object
                    properties:
                        referral link: { type: string, example: 'string'}
                        name: { type: string, example: 'string'}
                        email: { type: string, example: 'string'}
    areas: # to filter documented areas
         
        path_patterns:
            - ^/api(?!(/doc|/doc.json)$) # Accepts routes under /api except /api/doc
         
