nelmio_api_doc:
    documentation:
        # servers:
        #   - url: http://api.example.com/unsafe
        #     description: API over HTTP
        #   - url: https://api.example.com/secured
        #     description: API over HTTPS
        info:
            title: Cometa_rest_api
            description: Affiliate programm 
            version: 1.0.0
        # components:
        #     securitySchemes:
        #         Bearer:
        #             type: http
        #             scheme: bearer
        #             bearerFormat: JWT
        # security:
        #     - Bearer: []
        paths:
            /api/user:
                get:
                    description: Get all users
                    tags:
                        - users
                    responses:
                        200:
                            description: ok
                            content: 
                                application/json: 
                                    schema:
                                        type: object
                                        properties:
                                            status: { type: string, example: 'ok'}
            /api/user/{userId}:
                post:
                    description: Show user
                    tags:
                        - users
                    parameters:
                        - in: query
                          name: user
                          required: true
                          schema:
                            type: string
                            
                    responses:
                        200:
                            description: user data
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: #/components/schemas/UserResponse
            /api/user/{id}:
                get:
                    description: Show user Id
                    tags:
                        - User management
                    parameters:
                        - in: path
                          name: userId
                          required: true
                          schema:
                            type: string
                    # parameters:
                        - in: path
                          name: email
                          required: true
                          schema:
                            type: string
                            
                    responses:
                        200:
                            description: user data Id
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: #/components/schemas/UserResponse
                    # parameters:
                    #     - in: query
                    #       name: name
                    #       schema:
                    #         type: string
                    # responses:
                    #     200:
                    #         description: name data
                    #         content: 
                    #             application/json: 
                    #                 schema: 
                    #                     $ref: #/components/schemas/UserResponse    
                # get:
                #     description: Show user
                #     tags:
                #         - user
                #     responses:
                #         200:
                #             description: ok
                #             content: 
                #                 application/json: 
                #                     schema:
                #                         type: object
                #                         properties:
                #                             status: { type: string, example: 'ok'}
            /api/pakege/new/{user_id}:
                post:
                    description: New pakage 
                    tags:
                        - Package management 
                    parameters:
                        - in: path
                          name: user_id
                          required: true
                          schema:
                            type: string
                        - in: query
                          name: referral_link
                          required: true
                          schema:
                            type: string
                        - in: query
                          name: pakage_table_id
                          required: true
                          schema:
                            type: string
                            
                    responses:
                        200:
                            description: New pakage
                            content: 
                                application/json: 
                                    schema: 
                                        $ref: #/components/schemas/UserResponse                                  
        # tags: 
        #    - name: User_user
        #      description: uuuuu_nnnnn
        #    - name: pakage_pakage

            
            

    areas: # to filter documented areas
         
        path_patterns:
            - ^/api(?!(/doc|/doc.json)$) # Accepts routes under /api except /api/doc
         
