controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

user_controller:
   path: /
   controller: App\src\Controller\UserController
   methods: [ GET ]

pakage_controller:
   path: /
   controller: App\src\Controller\PakageController
   methods: [ GET ]
   