controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

user_controller:
   path: /api/user
   controller: App\src\Controller\UserController
   methods: [ GET ]

pakege_controller:
   path: /api/pakege
   controller: App\src\Controller\PakegeController
   methods: [ GET, POST ]

list_referral_networks_controller:
   path: /api/referral
   controller: App\src\Controller\ListReferralNetworksController
   methods: [ GET, POST ]

referral_network_controller:
   path: /api/network
   controller: App\src\Controller\ReferralNetworkController
   methods: [ GET, POST ]
   